<!DOCTYPE html>
<html lang="en">
	<head>
    	<!-- Meta Data -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="keywords" content="">
        <meta name="author" content="Webpentagon">
        <title>Yapnaa</title>
		<!-- Short cut favicon Icon Link-->
       	<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
		
		<!-- all fonts -->
		<link rel="stylesheet" href="css/fonts.css">
		<!-- fontAwesome Icon's -->
		<link rel="stylesheet" href="css/font-awesome.min.css" type="text/css">
        <!-- Bootstrap main css File -->
        <link rel="stylesheet" href="css/bootstrap.min.css">
		<!-- lightbox -->
		<link rel="stylesheet" href="css/lightbox.css">
		<!-- owl-carousel -->
        <link rel="stylesheet" href="css/owl.theme.css">
        <link rel="stylesheet" href="css/owl.carousel.css">
		
		<!-- main style.css File -->
        <link rel="stylesheet" href="css/style.css">
		<!-- media file css -->
        <link rel="stylesheet" href="css/responsive.css">
		
		<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
		
		<!-- all fonts -->
		<link rel="stylesheet" href="css/fonts.css">
		<!-- fontAwesome Icon's -->
		<link rel="stylesheet" href="css/font-awesome.min.css" type="text/css">
        <!-- Bootstrap main css File -->
        <link rel="stylesheet" href="css/bootstrap.min.css">
		<!-- lightbox -->
		<link rel="stylesheet" href="css/lightbox.css">
		<!-- owl-carousel -->
        <link rel="stylesheet" href="css/owl.theme.css">
        <link rel="stylesheet" href="css/owl.carousel.css">
		
		<!-- main style.css File -->
        <link rel="stylesheet" href="css/style.css">
		<!-- media file css -->
        <link rel="stylesheet" href="css/responsive.css">
		
		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

		  ga('create', 'UA-88944414-1', 'auto');
		  ga('send', 'pageview');
		</script>
	</head>

<?php include('header.php') ?>

<h2 class="text-center">TERMS & CONDITIONS</h2>
<p style="padding:40px;text-align:justify;">
	This document is an electronic record in terms of Information Technology Act, 2000 as amended from time to time and rules, regulations there under as applicable and the provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.<br><br>

The domain name www.yapnaa.com (hereinafter referred to as "Website" or “site”) and the application Yapnaa are owned by MoviloGlobal, a company incorporated in India under Companies Act, 2013, and having its registered office at: E-83, Rangappa Street, Chikkamavalli, Bangalore – 560 004, Karnataka. (hereinafter referred to as the “company” or “Yapnaa” or “intermediary” or “platform” or “application”).<br><br>

Please read the following terms and conditions carefully before registering, accessing, browsing, downloading or using the Site/application. By accessing or using the Site/APPLICATION or by using the Service through the website/application you agree to be bound by these terms and conditions set forth below including any additional guidelines and future amendment & modifications. If at any time you do not agree to these terms and conditions or do not wish to be bound by these terms and conditions, you may not/should not access or use the site and immediately terminate your use of the services.<br><br>

Your Agreement to these Terms and Conditions for availing Service from yapnaa.com is a legal contract between you any individual of at least 18 years of age or legal person who has agreed to become a user of service on the Website/platform/application by providing Registration Data while registering on the Website as Registered User using the computer systems or using the website/platform/application as Guest User and Yapnaa, having its registered office at # E-83, Rangappa Street, Chikkamavalli, Bangalore – 560 064, Karnataka, India.<br><br>

All services are rendered by Yapnaa through its platform and application under the brand name Yapnaa or Yapnaa. Hence all the rights, benefits, liabilities & obligations under the following terms & conditions shall accrue to the benefit of ‘ARATRA’. (together with its subsidiaries and other affiliates, “us”, “We” or “automobi.in”), regarding your use of our services listed in our website/application.<br><br>

DEFINITIONS & INTERPRETATIONS –<br><br>
<br>
“intermediary” means an intermediary as defined in R. 2(1)(i) of the IT (Intermediaries Guidelines) Rules, 2011 and as defined in S. 2(1)(w) of the IT Act, 2000 and in the present instant case to Yapnaa ;<br>

“Platform” means the service being operated online by MoviloGlobal in the name and style of yapnaa.com or through mobile application Yapnaa;<br><br>

“vendor” or ‘merchant’ in the instant case refers to the third party service provider listed in the website/application/portal; “User” shall refer to both the vendor/merchant/service provider listed in the platform and the purchaser/buyer of the service and products using the platform;<br><br>

“purchaser” or “customer” means a person acquiring a service or a product by payment of a consideration through the platform; “Application” shall mean the application developed by the company and offered by the company/yapnaa.com and downloaded and installed by you on your mobile device or other compatible device;<br><br>

“Driver” or "Drivers" shall mean the driver engaged by you by using our Website/Application; “sensitive personal data or information” shall have the same meaning as enumerated in Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011;<br><br>

PRIVACY:<br><br>

Please view our Privacy Policy, which also governs your use of yapnaa.com Services, to understand our practices and policies.<br><br>

ELIGIBILITY:<br><br>

3.1 Use of the Website/platform/application provided by ‘ARATRA’ is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 are not eligible to use the Website/platform/application. If you are a minor i.e. under the age of 18 years, you shall not register as a User of the yapnaa.com or the platform and shall not transact on or use the website/platform/application. As a minor if you wish to use or transact on website/application, such use or transaction may be made by your legal guardian or parents on the Website. yapnaa.com or ARATRA reserves the right to terminate your account with yapnaa.com or its application and / or refuse to provide you with access to the Website/application if it is brought to the company’s notice or if it is discovered that you are under the age of 18 years.<br><br>

3.2 You shall not impersonate any person or entity, or falsely state or otherwise misrepresent identity, age or affiliation with any person or entity.<br><br>

yapnaa.com ACCOUNT REGISTRATION OR GUEST USER:<br><br>

4.1 By using/logging into this website/application you intend to use the platform/yapnaa.com or service by Yapnaa and may opt for the option to create a User/Customer account or access as a Guest User. In case of User account you shall be responsible for maintaining the confidentiality of your Display Name and Password and You shall be responsible for all activities that occur under your Display Name and Password.<br><br>

4.2 For both User/customer account and Guest User You shall provide information that is true, accurate, current and complete. If yapnaa.com have any reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of your membership on the Website and refuse to provide You with access to the Website.<br><br>

TERMINATION OF yapnaa.com ACCOUNT:<br><br>

You agree that yapnaa.com, in its sole discretion, for any or no reason, and without penalty, may suspend or terminate your account (or any part thereof) or your use of the Services and remove and discard all or any part of your account, your user profile, or your recipient profile, at any time. yapnaa.com may also in its sole discretion and at any time discontinue providing access to the Services, or any part thereof, with or without notice. You agree that any termination of your access to the Services or any account you may have or portion thereof may be effected without prior notice, and you agree that yapnaa.com will not be liable to you or any third party for any such termination. Any suspected fraudulent, abusive or illegal activity may be referred to appropriate law enforcement authorities. These remedies are in addition to any other remedies yapnaa.com may have at law or in equity. Upon termination for any reason, you agree to immediately stop using the Services.<br><br>

COMMUNICATION & TRANSACTION THROUGH THE PLATFORM<br><br>

6.1 The Website is a platform that Users utilize to meet and interact with one another for their transactions. Yapnaa is not and cannot be a party to or control in any manner any transaction between the Website's/application Users<br><br>

Thus:<br><br>

All commercial/contractual terms are offered by and agreed to between the Users alone i.e., the third party service provider/seller/vendor listed in this website/application and the customer/user of the service/purchaser. Yapnaa does not have any control or does not determine or advise or in any way involve itself in the offering or acceptance of such commercial/contractual terms between the third party service provider/seller/vendor listed in the website Yapnaa and the customers/users of the service/purchaser.<br><br>

Yapnaa does not make any representation or Warranty as to specifics (such as quality, value, durability, competitiveness, etc) of the products or services proposed to be sold or offered to be sold or purchased on the Website. Yapnaa does not implicitly or explicitly support or endorse the sale or purchase of any products or services on the Website. Yapnaa accepts no liability for any errors or omissions, whether on behalf of itself or third parties.<br><br>

Yapnaa is not responsible for any non-performance or breach of any contract entered into between third party service providers/seller/vendors and purchaser of the service/product. Yapnaa cannot and does not guarantee that the concerned purchaser and/or service provider/vendor shall perform any transaction concluded on the Website/application. Though effort shall be made to mediate for any dispute which arises between the users of the platform Yapnaa but Yapnaa shall not be obligated and is not required to mediate or resolve any dispute or disagreement between Users of the website/application.<br><br>

Yapnaa does not make any representation or warranty as to the identity, legal title, credibility, background, etc. of any of its Users. You are advised to independently verify the bona fides of any particular User that You choose to deal with on the Website/application and use Your best judgment in that behalf.<br><br>

The Website/application is only a platform that can be utilized by Users to reach a larger base to buy and sell products or services. Yapnaa is only providing a platform for communication and it is agreed that the contract for sale of any of the products or services shall be a strictly bipartite contract between the vendor/merchant/third party service provider and the purchaser/buyer/user of the service or the product.<br><br>

At no time shall Yapnaa hold any any right, title or interest over the vehicle, spares, products nor shall Yapnaa have any obligations or liabilities in respect of such contract.<br><br>

Yapnaa is not responsible for unsatisfactory or delayed performance of services or damages or delays by the third party service provider/vendor/merchant listed on the platform and opted by the purchaser of the service/user through the platform Yapnaa.<br><br>

WARRANTIES AND LIABILITY:<br><br>

7.1 This Website, all the materials and services (including but not limited to software) and products, included on or otherwise made available to You through this site are provided on "as is" and "as available" basis without any representation or warranties, express or implied except otherwise specified in writing. Without prejudice to the forgoing paragraph, Yapnaa does not warrant that:<br><br>

7.1.1 This Website will be constantly available, or available at all; or<br><br>

7.1.2 The information on this Website is complete, true, accurate or non-misleading.<br><br>

7.2 Yapnaa will not be liable to You in any way or in relation to the Contents of, or use of, or otherwise in connection with, the Website/application. Yapnaa does not warrant that this site; information, Content, materials, product (including software) or services included on or otherwise made available to You through the Website; their servers; or electronic communication sent from Us are free of viruses or other harmful components.<br><br>

7.3 Nothing on Website/application constitutes, or is meant to constitute, advice of any kind. All the services rendered through the website are governed by different state laws and if vendor/merchant is unable to deliver such services and Products due to implications of different state laws, vendor/merchant shall return or shall give credit for the amount (if any) received in advance by vendor/merchant from the sale of such services and Products that could not be delivered to You.<br><br>

7.4 You will be required to enter a valid phone number while placing an order on the Website. By registering Your phone number with us, You consent to be contacted by Us via phone calls and/or SMS notifications, in case of any order or confirmation related updates. We will not use your personal information to initiate any promotional phone calls or SMS unless allowed by you or opted by you.<br><br>

VENDORS/MERCHANTS:<br><br>

8.1 As a registered vendor/merchant/user, you are representing that you own or are an Authorized representative of a legal entity or an Individual or a proprietary concern and are allowed by the laws of India to render services or sell products in India and are allowed to list services, products for sale on the Website/application in accordance with the Policies which are incorporated by way of reference in this Terms & Conditions for User or in accordance with separate agreement entered with You. You must be legally able to offer services or sell the item(s) you list for sale on our Website/application. You must ensure that the listed items do not infringe upon the intellectual property, trade secret or other proprietary rights or rights of publicity or privacy rights of third parties. Listings may only include text descriptions, graphics and pictures that describe your service or your product/item for sale. All listed services and products must be listed in an appropriate category on the Website.<br><br>

8.2 The listing description of the service or the product must not be misleading and must describe actual offering. If the service on offer or the product description does not match the actual offering or the product, you agree to refund any amounts that you may have received from the Purchaser of the service or the Product. You agree to list service or Product in the right category and Yapnaa reserves the right to delete wrong listings of the services or the product listed by you in various categories.<br><br>

PICK-UP OF THE VEHICLE AND LIABILITY FOR LOSS:<br><br>

The VENDOR/MERCHANT may prefer rendering the service of pick-up of the vehicle from the place of the vehicle owner to the workshop/garage and shall ensure before pick-up that the vehicle have valid insurance cover and any damage, accident, any incident directly, indirectly, creating loss for the vehicle and the vehicle owner, while the vehicle is in the possession of the Vendor/Merchant, shall be the responsibility of the vehicle owner and the Vendor/Merchant, and any claim, legal actions arising from loss to the vehicle, shall be between the vehicle owner and the Vendor/Merchant and the User herein agrees not to hold the platform/website/application or the company responsible for the same.<br><br>

SERVICES:<br><br>

Fine Tune, Spa, Flat Tyre, Vehicle washing, Emergency services:<br><br>

Yapnaa.com is not an Authorized service station or a service station or a tyre repair shop or a vehicle spa or any vehicle emergency service station on its own and is a platform which connects the service station/authorized service station/tyre repair shop/vehicle washing centre/vehicle emergency service provider and the user enquiring about the above services. yapnaa.com is not a warrantor, insurer, or guarantor of the services to be provided by the service station/authorized service station/tyre repair shop/ vehicle washing centre/vehicle emergency service provider. Services or products sold/offered through the website/application of yapnaa.com are sold/offered without recourse against us for any breach of contract by the third party service provider or seller. Any disputes regarding the quality, minutes provided, spares, cost, expiration, or other terms of the service offered or products sold must be handled directly between You (or the recipient of the service or the product) and the third party service provider or the product seller.<br><br>

Hire Chauffeur:<br><br>

Yapnaa.com   does not employ any driver(s) and is a platform allowing listing of drivers representing themselves to be legally allowed to drive in India and complying with all Central/State laws and directions from the law enforcement agencies pre-requisite to be eligible to drive in India.<br><br>

Yapnaa connects through its website/application/platform the Users requesting service of driver(s)/chauffeur for a specific time/day/month/year with the available driver(s) on its platform. Users may send request to Yapnaa for Chauffeur service but the platform/company does not guarantee driver(s)/chauffeur to the Users and Users requesting for service are only connected to the available driver(s)/chauffeur.<br><br>

Conditions for Use of ‘Hire Chauffeur’ service:<br><br>

That you represent, confirm and warrant that you have the rightful legal authority to drive/possess/hold the vehicle and engage drivers for the vehicle.<br><br>

That the vehicle(s) have valid Registration with the Transport Department and/or the competent authority for plying in India and/or any specific State(s) in India.<br><br>

That you represent that there is a valid insurance cover for the vehicle from IRDA recognised insurance service provider and for which Chauffeur service has been requested through the platform.<br><br>

Yapnaa carries out a thorough check of the drivers and their background, the relevant documents but the quality of the Services requested through the use of the website/Application is entirely the responsibility of the Driver who ultimately provides such services to you. Yapnaa under no circumstance accepts liability in connection with and/or arising from the Services provided by the Driver or any acts, actions, behaviour, conduct, and/or negligence on the part of the Driver.<br><br>

You will be solely responsible for the full functionality of your vehicle. If your vehicle fails to function (electrical, mechanical or other) in any way while the Services are being availed of by you, you will be responsible for all incidental expenditure, roadside assistance, alternate transportation and repair of any kind and neither Yapnaa shall be responsible in any manner whatsoever. You have the legal right to designate the Driver as your agent and delegate actual authority to the Driver to operate your vehicle and make decisions on your behalf for the purposes of providing Services offered through the Yapnaa platform.<br><br>

In the event of a motor vehicle accident you will be solely responsible for compliance with any applicable laws, rules and regulations including responding and complying with any court notices, orders, directions including satisfaction of any liability and for all necessary contacts with your insurance provider.<br><br>

The pricing for ‘Hire Chauffeur’ service shall be as shown on the website/application at the moment the service is requested/booked through the platform and shall be a dynamic/variable pricing depending upon various factors including availability/time of the day/others.<br><br>

The offer of the service, the manner in which it is offered, amendment to the conditions are at the sole discretion of the platform/company/yapnaa.com and Users are required to refer to the Terms & Conditions as updated/amended from time to time.<br><br>

INDIAN UNITS<br><br>

11.1 All amounts displayed on the website, application, proposal, invoices, and in the Yapnaa published price list and in the Yapnaa Application Form are in Indian Rupees (INR).<br><br>

11.2 Time is provided in Indian Standard Time (IST) as it exists presently in India.<br><br>

PAYMENTS<br><br>

12.1 Subject to any other specific payment terms being agreed upon in writing by Yapnaa and you or through any other legally binding electronic medium between Yapnaa and you, you agree payment of any and all amount(s) and associated fees in relation to the transaction(s) you or members of your organisation authorise and/or process using the Yapnaa website/application facility or any other Yapnaa service or product shall be made through the Internet Banking channels available in the website/application or the payment may be made directly to the vendor/merchant in cash/POS/any other medium/channels available with the vendor/merchant and acceptable by the vendor/merchant.<br><br>

12.2 While availing any of the payment method/s available on the website/application, we will not be responsible or assume any liability, whatsoever in respect of any loss or damage arising directly or indirectly to You due to:<br><br>

Lack of authorization for any transaction/s, or<br>

Exceeding the preset limit mutually agreed by You and between "Bank/s", or<br>

Any payment issues arising out of the transaction, or<br>

Decline of transaction for any other reason/s.<br><br>

12.3 The User/customer receives an approximate estimation from the vendor/merchant for the service he/she requested from the third party service provider through the platform/yapnaa.com and after receiving the estimation, and if the same exceeds Rs 8,000/-, the User/customer needs to make an advance payment of 40% to 50% of the estimation depending upon the requirement and which shall be primarily used to procure spares, goods, materials, products required for completing the service. The rest of the payment needs to be made at the time of taking delivery of the vehicle.<br><br>

12.4 The vehicle(s) of the user/customer availing service from the website/application are released by the vendor/merchant on receiving full payment from the user of the service.<br><br>

PAYMENT FOR CHAUFFEUR SERVICE:<br><br>

13.1 Payment for the Chauffeur service may be made at the time of booking through the platform/yapnaa.com and charges for additional time being used should be paid at the end of the service as per rate schedule agreed at the time of opting for the service.<br><br>

13.2 The payment can also be made as per rate schedule in full at the end of the service to the chauffeur or online through website/application/yapnaa.com.<br><br>

The present rates are as follows:<br><br>

Sl. No.	DESCRIPTION	RATE/HOUR(Rupees)
1.	One way Chauffeur/driver service from 6 am to 9 pm	100.00 per hour
2.	One way Conveyance charges from 6 am to 9pm (in addition to per hour chauffeur charges)	100.00 on overall Bill
3.	One way Chauffeur/driver service from 9 pm to 6 am	200.00 per hour
4.	One way Conveyance charges from 9 pm to 6 am (in addition to per hour chauffeur charges)	200.00 on Overall Bill
5.	Round way Chauffeur/driver service from 6 am to 9 pm	100.00 per hour
6.	Round way Chauffeur/driver service from 9 pm to 6 am	200.00 per hour
7.	Outstation charges (6 am to 9 pm)	450.00 per day
8.	Outstation charges (9 pm to 6 am)	550.00 per night
*Service tax shall be added wherever applicable.<br><br>

13.3 The Users/Customers need to Hire Chauffeur/driver for a minimum duration of 2 hours for a single trip or make payment for a minimum duration of 2 hours for hiring Chauffeur through the platform/yapnaa.com/ARATRA even when the trip time is less than 2 hours.<br><br>

13.4‘Automobi.in’ or ‘ARATRA’ may modify, amend, change, vary, the pricing structure and the Service description at its sole discretion any time in the future without any prior notice to the registered users/customers or any other party directly/indirectly involved in the platform/yapnaa.com/company.<br><br>

PAYMENT FOR FLAT TYRE & REPAIR SERVICE:<br><br>

Payment for flat tyre service and other repair service for 2, 3, 4 wheelers may be made through the platform/yapnaa.com or to the vendor directly as per the final bill amount generated by the vendor.<br><br>

The present rates for flat tyre service are as follows:<br><br>

Sl. No.	DESCRIPTION	RATE(Rs./ per puncture)
1.	When user avails service for 2 wheeler and visits the repair shop directly w/o availing pick up service	70.00
2.	When user avails service for 2 wheeler and request for a pick- up service	100.00
3.	When user avails service for 4 wheeler and visits the repair shop directly w/o availing pick up service	100.00
4.	If user avails service for 4 wheeler and request for a pick- up of the vehicle and the vendor picks up the vehicle from the address of the user	150.00
*Service tax shall be added wherever applicable.<br><br>

SENSITIVE PERSONAL DATA OR INFORMATION:<br><br>

15.1 The sensitive personal data or information as described in the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011, shall be dealt in the manner prescribed under the Rules, the parent Act and the company/body corporate/yapnaa.com shall be complying with all future laws, rules, regulations for protecting the sensitive personal data or information.<br><br>

15.2 The payments done by the users/customers through yapnaa.com are all processed through a secure server and completed through third party payment gateway provider and yapnaa.com does not hold, save, retain any credit card information/passwords/internet banking details and other details used by users/customers for making any payments.<br><br>

CANCELLATION & REFUND:<br><br>

16.1 Cancellation by Vendor or yapnaa.com: There may be certain service request that yapnaa.com Vendors/Merchants are unable to accept and service and these may need to be cancelled. Some situations that may result in your order being cancelled include, non-availability service in the address/location provided by the user/customer, inaccuracies or errors in pricing information specified by our Vendors/Merchant listed on yapnaa.com, or problems identified by Yapnaa.incredit and fraud avoidance department. yapnaa.com may also require additional verifications or information before accepting any order. yapnaa.com will contact you if all or any portion of your order is cancelled or if additional information is required to accept your order. If your order is cancelled after your credit card or bank account has been charged, the said amount will be reversed back in your credit card / bank account.<br><br>

16.2 Cancellation by User/Customer: In case of requests for order cancellations,yapnaa.com reserves the right to accept or reject requests for order cancellations for any reason whatsoever. As part of usual business practice, ifautomobi.inreceives a cancellation notice and the order has not been processed/ approved by yapnaa.com, yapnaa.com shall cancel the order and refund the entire amount to you instantly. yapnaa.com will not be able to cancel orders that have already been processed or arrangement/spares/products/goods already procured based on the order. yapnaa.com has the full right to decide whether an order has been processed or not. You agree not to dispute the decision made by yapnaa.com and accept yapnaa.com decision regarding the cancellation.<br><br>

16.3 Yapnaa is reliant on third parties such as banks to deliver timely Services and process refund. Since, Yapnaa cannot control the actions of such third parties, Yapnaa will not be responsible to render Services or process payments or refunds on the following days ("Non - Working Days"):<br><br>

16.3.1 days which are declared as holidays by the RBI, or any other day which is declared a holiday by Us.<br><br>

16.3.2 days including Saturdays and Sundays and declared as bandhs or festivals in any State or Union Territory in India. We will continue to render Services which do not involve that particular State or Union Territory in which a bandh or festival has been declared on that day.<br><br>

COPYRIGHT:<br><br>

All content included in or made available through any yapnaa.com Service, such as text, graphics, logos, button icons, images, audio clips, digital downloads, data compilations, and software is the property of yapnaa.com or its content suppliers and protected by the Indian copyright laws. The compilation of all content included in or made available through any yapnaa.com Service is the exclusive property of Yapnaa and protected by Indian copyright laws.<br><br>

INTELLECTUAL PROPERTY RIGHTS:<br><br>

We or Yapnaa, or our licensors, own all right, title and interest, including, but not limited to all copyright, trademark, patent, trade secret or other proprietary rights (“IP Rights”), in and to the Site/application, the Platform, the Usage Data. You shall not reproduce, distribute, transmit, modify, create derivative works, display, perform or otherwise use the Site, the Platform or any of the IP Rights, or attempt to reverse engineer, decompile, disassemble, or derive the source code for the Platform or use the Platform or Site to create a competing product. yapnaa.com is owned by Yapnaa. Unauthorized use is strictly prohibited. All rights are expressly reserved to Yapnaa.

. LIMITATION OF LIABILITY:

19.1 Yapnaa shall not be liable for indirect, incidental, special, exemplary, punitive, or consequential damages, including lost profits, lost data, personal injury, or property damage related to, in connection with, or otherwise resulting from any use of the services, even if Aratra or yapnaa.com has been advised of the possibility of such damages. Aratra or yapnaa.com shall not be liable for any damages, liability or losses to you or any third party arising out of: (i) use of or reliance on the services/platform/application of the company or Yapnaa.com or inability to access or use the services/platform/application of the company; or (ii) any transaction or relationship between the company and you or any third parties, even if ‘Aratra’ or yapnaa.com has been advised of the possibility of such damages. Aratra orautomobi.in shall not be liable for delay or failure in performance resulting from causes beyond Aratra or yapnaa.com reasonable control.<br><br>

19.2 Without prejudice to the foregoing, and insofar as allowed under mandatory applicable law, the aggregate liability of the Platform/company/yapnaa.com shall in no event exceed the equivalent of the amount received by the platform/company/yapnaa.com out of the total payments made for the service/products.
EXTENT OF ACCESS & LICENSE:<br><br>

Subject to your compliance with these Terms & Conditions of Use and your payment of any applicable fees, yapnaa.com or its content providers grant you a limited, non-exclusive, non-transferable, non-sub licensable license to access and make personal and non-commercial use of the Yapnaa Services. This license does not include any resale or commercial use of any ARATRA Service, or its contents; any collection and use of any service listings, descriptions, or prices; any derivative use of any ARATRA Service or its contents; any downloading, copying, or other use of account information for the benefit of any third party; or any use of data mining, robots, or similar data gathering and extraction tools. All rights not expressly granted to you in these Terms & Conditions of Use or any Service Terms are reserved and retained by ‘ARATRA’ or its licensors, service providers, suppliers, publishers, rights holders, or other content providers. No Service, nor any part of any yapnaa.com Service, may be reproduced, duplicated, copied, sold, resold, visited, or otherwise exploited for any commercial purpose without express written consent of yapnaa.com or ARATRA. You may not frame or utilize framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of yapnaa.com without express written consent. You may not use any meta tags or any other "hidden text" utilizing yapnaa.com or ARATRA name or trademarks without the express written consent of ARATRA. You may not misuse the yapnaa.com or ARATRA Services. You may use the Services listed in the website/application only as permitted by law. The licenses granted by yapnaa.com or ARATRA terminate if you do not comply with these Terms & Conditions of Use or any related Service Terms.<br><br>

USER REVIEWS AND COMMENTS:<br><br>

Users may post reviews, comments, photos, videos, and other content; or any other form of feedback/communication; and submit suggestions, ideas, comments, questions, or other information, so long as the content is not illegal, obscene, threatening, defamatory, invasive of privacy, infringing of intellectual property rights, or otherwise injurious to the company or any third parties or any user or objectionable, and does not consist of or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings, or any form of "spam" or unsolicited commercial electronic messages. You may not use a false e-mail address, impersonate any person or entity, or otherwise mislead as to the origin of a particular communication or other content. yapnaa.com or ARATRA reserves the right (but not the obligation) to remove or edit such content, but does not regularly review posted content.<br><br>

INDEMNIFICATION:<br><br>

22.1 The User of the platform/website/application agrees that yapnaa.com is not liable for any direct, indirect, incidental or consequential loss or damage by reasons not within the control of the platform and that may occur through the use of your site, and the user/customer agrees to indemnify yapnaa.com and hold harmless yapnaa.com or ARATRA, its subsidiaries, affiliates and their respective officers, directors, agents and employees, from any claim or demand, or actions including reasonable lawyer fees, made by any third party or penalty imposed due to or arising out of your breach of these Terms & Conditions of Use or any document incorporated by reference, or your violation of any law, rules, regulations or the rights of a third party.<br><br>

22.2 You hereby expressly release 'ARATRA'and/or its affiliates and/or any of its officers and representatives from any cost, damage, liability or other consequence of any of the actions/inactions of the vendors and specifically waiver any claims or demands that you may have in this behalf under any statute, contract or otherwise.<br><br>

AMENDMENT & MODIFICATION OF TERMS & CONDITIONS:<br><br>

yapnaa.com reserves the right, at its sole discretion, to revise, add, or delete portions of these terms and conditions any time without further notice. You shall re-visit the “Terms & Conditions” link from time to time to stay abreast of any changes that the website/application/company may introduce.<br><br>

RIGHTS TO THE PLATFORM:<br><br>

If you do post content or submit material, and unless we indicate otherwise, you grant yapnaa.com or ARATRA a nonexclusive, royalty-free, perpetual, irrevocable, and fully sublicensable right to use, reproduce, modify, adapt, publish, perform, translate, create derivative works from, distribute, and display such content throughout the world in any media. You grant yapnaa.com or ARATRA and sublicensees the right to use the name that you submit in connection with such content, if they choose. You represent and warrant that you own or otherwise control all of the rights to the content that you post; that the content is accurate; that use of the content you supply does not violate this policy and will not cause injury to any person or entity; and that you will indemnify yapnaa.com or ARATRA for all claims resulting from content you supply. yapnaa.com or ARATRA has the right but not the obligation to monitor and edit or remove any activity or content. Yapnaa.intakes no responsibility and assumes no liability for any content posted by you or any third party.<br><br>

DISPUTES & GOVERNING LAWS:<br><br>

25.1 In case of any dispute between the parties, either party may notify the other in writing of the substance of the complaint, and the dispute shall first be referred to mediation and efforts shall be made for amicable settlement of the matter by the parties.<br><br>

25.2 This agreement shall be governed by and constructed in accordance with the laws of India without reference to conflict of laws principles and disputes arising in relation hereto if not settled by mediation shall be subject to the exclusive jurisdiction of the courts at Bangalore, Karnataka, India.<br><br>

WAIVER:<br><br>

The failure of yapnaa.com or ARATRA to exercise or enforce any right or provision of this Agreement will not constitute a waiver of such right or provision. Any waiver of any provision of this Agreement will be effective only if in writing and signed by yapnaa.com or ARATRA .<br><br>

NOTICES:<br><br>

Any and all notices, demands, or other communications required or desired to be given hereunder by any party shall be in writing and shall be validly given or made to another party if personally served. If such notice or demand is served personally or through email from the registered email id, notice shall be deemed constructively made at the time of such personal service. If such notice, demand or other communication is given by postal mail, such notice shall be conclusively given 15 days after deposit thereof in India and from India to the party to whom such notice, demand or other communication is to be given.<br><br>

HEADINGS:<br><br>

The headings and subheadings herein are included for convenience and identification only and are not intended to describe, interpret, define or limit the scope, extent or intent of the agreement and its clause contained herein or any other section in any manner whatsoever.<br><br>

RESPONSIBLE DISCLOSURE:<br><br>

At yapnaa.com, we take the security of our systems seriously, and it is our constant endeavour to make our website/application a safe place for our users/customers to browse. However, in the rare case when some security researcher or member of the general public identifies a vulnerability in our systems, and responsibly shares the details of it with us, we appreciate their contribution, work closely with them to address such issues with urgency, and if they want, publicly acknowledge their contribution.<br><br>

DISCLAIMER:<br><br>

30.1 You acknowledge and undertake that you are accessing the services on the website and transacting at your own risk and are using your best and prudent judgment before entering into any transactions through the website. We shall neither be liable nor responsible for any actions or inactions of vendors/merchants/sellers listed on the website/application nor any breach of conditions, representations or warranties by the vendors/merchants/sellers of the service/products or manufacturers of the products and hereby expressly disclaim and any all responsibility and liability in that regard. We shall not mediate or resolve any dispute or disagreement between you and the vendors/merchants/sellers of the service/products or manufacturers of the products.<br><br>

30.2 We further expressly disclaim any warranties or representations (express or implied) in respect of quality, suitability, accuracy, reliability, completeness, timeliness, performance, safety, merchantability, fitness for a particular purpose, or legality of the services offered by the third party service providers or any products listed or displayed or transacted or the content including pricing information and/or specifications on the website. While we have taken precautions to avoid inaccuracies in content, this website, all content, information (including the price of products), software, products, services and related graphics are provided as is, without warranty of any kind. We do not implicitly or explicitly support or endorse the sale or purchase of any service/products on the website. At no time shall any right, title or interest in the service/products sold through or displayed on the website vest with yapnaa.com nor shall yapnaa.com have any obligations or liabilities in respect of any transactions on the website.<br><br>

CLARIFICATION:<br><br>

For any clarification the users/customers may feel free to write us at info@moviloglobal.com<br><br>
</p>
<?php include('footer.php') ?>